<a href="https://colab.research.google.com/github/helah20/Python/blob/main/LinearAlgebraAssignmentP5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# **practices**

In [2]:
np.random.rand(3,3)

array([[0.9124641 , 0.65331942, 0.86116871],
       [0.80665505, 0.5388639 , 0.6814485 ],
       [0.03767426, 0.94926775, 0.18878751]])

In [6]:
np.random.rand(3,3).size


9

In [7]:
np.random.rand(3,3).shape

(3, 3)

In [9]:
np.random.randint(3,10)

4

In [11]:
np.random.randint(3,10,(2,3))

array([[4, 6, 8],
       [3, 6, 5]])

## **asinment solution**

## **Use your Jupyterlab environment and numpy from your MatrixDS project to solve the attached systems of equations. What values do you get for x and y for each?**
first:

3x + 5y = 6

7x - 5y = 9




In [18]:
A=np.array([[3,5],[7,-5]])
B=np.array([6,9])
x=np.linalg.inv(A).dot(B)

print(x)

[1.5 0.3]



x + y + z = 6
 
y + z = -4

2x + 5y - z = 27


In [19]:
A=np.array([[1,1,1],[0,1,1],[2,5,-1]])
B=np.array([6,-4,27])
x=np.linalg.inv(A).dot(B)

print(x)

[10.   0.5 -4.5]


x + y = 4

2x + 2y = 8

In [21]:
A=np.array([[1,1],[2,2]])
B=np.array([4,8])
x=np.linalg.inv(A).dot(B)

print(x)
# the error becuz the variable have the same value 

LinAlgError: ignored

We also did the Assignment by hand 

# First system of equation
3x + 5y = 6

3x = 6 -5y

x = (6 -5y)/3

x = 2-(5y/3)
_____________
replace y:
**x = 2-(5y/ 3)**

x = 2-(5-0.325/ 3)

**x = -2.8916**
___________
find x:

7x - 5y = 9

7(2-(5y/3)) - 5y = 9

14 - 35y/3 -5y = 9

14 -35y -5y = 27

14 -40y = 27

-40y = 27 - 14

-40y = 13

**y = -0.325**

# Second system of equation

x + y + z = 6

   y + z = -4

2x + 5y - z = 27


 combine 1&2 equation

x + 2y + 2z = 2

combine 2&3 equation

2x +6y = 23

x = 11.5 -6y 
--------
add y value

x = 11.5 -6 * 0.25

x = 10

find y 
11.5 -6y + 2y + 2z = 2

11.5 -2 +2z = 4y

9.5 +2z = 4y

y = 2.375 +0.5z

--------
add z value

y = 2.375 +0.5 * -4.25

y = 0.25

find z

2.375 +1.5z = -4

1.5z = -4 - 2.375

1.5z = -6.375

z = -4.25

# Third system of equation
x + y = 4

x = 4 - y

2x + 2y = 8

2 (4-y) + 2y = 8

8 -2y +2y = 8

8 = 8

-2y +2y = 8 - 8

0 = 0